intl = {
"currency":"//button[@id='currencyCode-button']",
'oneway' : "//input[@class='seleniumCarOneWay']",
"pickup_loc" : "//input[@name='pickupLocation']",
"dropoff_loc" : "//input[@name='dropOffLocation']",
"pickup_date" :"//input[@name='startDate']",
"dropoff_date" :"//input[@id='endDateCalendarCar-field']",
"age":"//input[@name='driverAge']",
"submit":"//button[@type='submit']",
"card":"seleniumCreditCardType",
"first_name":"//input[@class = 'seleniumFirstName']",
"last_name":"//input[@class = 'seleniumLastName']",
"email":"//input[@class = 'seleniumEmailAddress']",
"conf_email":"//input[@class = 'seleniumConfirmEmailAddress']",
"phone":"//input[@id = 'carDriver.phoneNumber']",
"address":"//input[@class = 'seleniumStreetAddress']",
"city":"//input[@class = 'seleniumCityAddress']",
"card_num":"//input[@class = 'seleniumCreditCardNumber']",
"card_mon":"//a[@id = 'cardExpiryMonth-button']",
"card_year":"//a[@id = 'cardExpiryYear-button']",
"card_code":"//input[@id = 'creditCard.securityCode']",
"accept":"//input[@class = 'seleniumDepositTypeTermsAccepted']",
}


